### ISSUE TITLE
Rename box2

### ISSUE THREAD

**Issue by keks** [ssbc/envelope-spec#14]
I am not sure whether I'm being pedantic, but I'll propose this anyway.

In the beginning, we called this box2 because it was supposed to be a thing that replaces the `content: "<base64>.box` encryption format of scuttlebutt and we thought it would just be version 2 of it. However, in the last calls we determined that this thing should not be specific to scuttlebutt.

The reason the old format had the `.box` suffix is the same why messages IDs have the `.sha256` suffix: they are named by the used algorithms, but actually describe the format, which is a significant source of complexity. The `box` algorithm name is from sodium, and if someone is not familiar with the history of how box2 came to pass, they may think it may be an iteration of the box from sodium. Everybody knows sodium boxes, less than a hundred people know about `content: "<base64>.box"`. Also, we'd be perpetuating the pitfall we walked into before: name the scheme after the used algorithm.

I propose naming it after what it actually does/is. This spec is about sending encrypted messages, with similar abstractions as email. We could call it `.msgbox` or `boxmail`. Another idea I had is `.envelope`, because that is what keeps our snail mail private. I think I like envelope better, because it is a proper word, but I'm also open for other suggestions. I don't want to start a huge bike shedding session, though, so if this turns out to stall the release of the spec I'd rather stick with box2.

**Comment by mixmix** [comment]
`envelope` is cute, I like it.

Note that on the ssb-side, we cant use the suffix `.envelope` at the moment, because there is validation of the ciphertext which checks its something like `<base64>.box.*`

so we can do `asdasdasdasd=.box2` or `sadasdasdasd=.box.envelope` (yuch!).

Can you clarify if we're talking about:
- a) renaming this spec
- b) renaming the suffixes

Ideally the two would be related to help people understand, and unfortunately the current starting point is we have `.box` suffix which is a bit general.

I don't mind too much TBH, this is a lot priority part for me, but I am happy to go for changes which don't involved large changes or ugliness <3

**Comment by mixmix** [comment]
closing this - it's now the envelope-spec
