### ISSUE TITLE
Don't use HMAC in external nonce

### ISSUE THREAD

**Issue by keks** [ssbc/envelope-spec#4]
Instead, just use both values in the key derivation directly. Maybe encode an object using bencode, that is a simple format, suits our needs (bijective) with many implementations. The object could look like
```
{
  "purpose": "box2",
  "type": "slot key",
  "feed": "@abc.[feedtype]",
  "prev": "%def.[msgtype]"
}
```
alternatively, we could just have an array of these values and treat it as a form of hierarchy:
```
["box2", "slot key", "@abc.[feedtype]", "%def.[msgtype]"]
```
Either would work fine, the latter probably is slightly more efficient because the output is shorter, so less data needs to be hashed.

**Comment by keks** [comment]
Example with a group key:
```
function deriveSlotKey(sharedKey, feed, prev) {
  infoObj = {
    "purpose": "box2",
    "type": "slot key",
    "feed": feed,
    "prev": prev
  }
  return hkdf.expand(key, bencode.Encode(infoObj))
}
```
Or, alternatively:
```
function deriveSlotKey(sharedKey, feed, prev) {
  infoArr = [ "box2", "slot key", feed, prev ]
  return hkdf.expand(key, bencode.Encode(infoArr))
}
```

Does this make sense?

**Comment by mixmix** [comment]
Couple of questions @keks  : 
1. are there typos - you take a `sharedKey` but don't use it anywhere. I presume that's the `key`
2. can you expand on what the problem is, you jump straight to a solution
  - what problem are you solving, why?
  - you mention external_nonce in title, but don't name it anywhere in body of what follow
3. Here's how I'm current deriving the "slot content", can we use the same vars to compare:
```
slot_content = xor(
  msg_key,
  DeriveSecret(recipient_key, external_nonce, 32)
)
```
4. I've assumed we can just use the `external_nonce` in the formation of the key-slot as it's unique enough.
  - did this to remove having to pass in "previous", but maybe that is a poor idea 
  - We need to talk about the slot_content derivation obviously!
5. is the `external_nonce` specification part of the box2-spec... ?


Not trying to be a picky jerk, there's just a bunch of moving parts here and I don't want to trip / missing anything!

**Comment by mixmix** [comment]
we agreed on dropping "external_nonce"
